---
title: "Untitled"
output: html_document
date: "2025-03-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(careless)
library(ggplot2)
library(car)
library(psych)
library(dplyr)
library(gtsummary)
library(lavaan)
library(tidySEM)
library(haven)
library(semTools)
library(corrplot)
library(lavaan)
```

Hypothesis 1 anovas for ssec and group

```{r anova}

####analyses
##anova
#1- freiwillig
#2- verpflichtend
#3 - control


#3 group
groupcom <- aov(ssec ~ c_0001+tsec, data=mand)
summary(groupcom)

#only manipulation
groupcom_man <- aov(ssec ~ c_0001, data=onlymanipulation)
summary(groupcom_man)
TukeyHSD(groupcom_man)

#comparisons with control are significant


```

need for freedom anovas

```{r}
#3 group
groupcom_free <- aov(sfree ~ c_0001, data=mand)
summary(groupcom_free)
TukeyHSD(groupcom_free)

#only manipulation
groupcom_manfree <- aov(sfree ~ c_0001, data=onlymanipulation)
summary(groupcom_manfree)
TukeyHSD(groupcom_manfree)

```

Hypotheses 5 and 6

```{r}
#H5: The perceived effectiveness of the proposed policy will not differ between 
#the mandatory and the voluntary conditions.
a <- aov(man_eff~c_0001, data=forsem_s)
summary(a)
TukeyHSD(a)
#mandatory policy seen as more effective
```

```{r}
#H6: Participants in the mandatory condition will perceive the policy to be less 
#acceptable in comparison to those in the voluntary and control conditions.

b <- aov(man_acc~c_0001, data=forsem_s)
summary(b)
TukeyHSD(b)


```

Plots for h5 and 6

```{r}


library(plyr)
legend_title <- "Group"
cdat <- ddply(onlymanipulation, "c_0001", summarise, rating.mean=mean(man_eff))
cdat
ggplot(onlymanipulation, aes(x=man_eff, color=c_0001)) + geom_density()+
  labs(color = "Group")+
  geom_vline(data=cdat, aes(xintercept=rating.mean,  colour=c_0001),linetype="dashed", linewidth=1)+
  xlab("Need for Security (State)")+
  scale_color_manual(labels = c("voluntary", "mandatory", "control"), values = c( "red","lightgreen")) 

with(onlymanipulation, aggregate(man_acc ~ c_0001, FUN = mean))

library(plyr)
legend_title <- "Group"
cdat <- ddply(onlymanipulation, "c_0001", summarise, rating.mean=mean(man_acc))
cdat
ggplot(onlymanipulation, aes(x=man_acc, color=c_0001)) + geom_density()+
  labs(color = "Group")+
  geom_vline(data=cdat, aes(xintercept=rating.mean,  colour=c_0001),linetype="dashed", linewidth=1)+
  xlab("Need for Security (State)")+
  scale_color_manual(labels = c("voluntary", "mandatory", "control"), values = c( "red","lightgreen")) 


```

Security

```{r}

med.model <- '
  needsecurity =~ ssec1+ssec2+ssec3
  Mainstream=~narrative_2  +narrative_4  +narrative_6  +narrative_8  
  Micronarratives=~narrative_1+narrative_3+narrative_5+ narrative_7 
  traitneedsecurity=~ tsec1+tsec2+tsec3
  Micronarratives ~b1*needsecurity+traitneedsecurity
  Mainstream ~b2*needsecurity+traitneedsecurity


  needsecurity ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1
  
ind1 := a1*b1
ind2 := a1*b2

'

med.fit <- sem(med.model, data = forsem, estimator = "ML", missing = "FIML",
               se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(med.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_med.fit <- parameterEstimates(med.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_med.fit)
estimates_med.fit[61:62, ]
```

```{r}
pfad_layout<- get_layout("","", "", "","Micronarratives",
                         "","needsecurity", "","","",
                         "","","","","",
                         "","","","","Mainstream",
                         "gr_1","","","","",
                         rows = 5)

tidySEM::graph_sem(model = med.fit, layout = pfad_layout) 
```

Trust - security

```{r}

tmed.model <- '
  needsecurity =~ ssec1+ssec2+ssec3
  Mainstream=~narrative_2  +narrative_4  +narrative_6  +narrative_8  
  Micronarratives=~narrative_1+narrative_3+narrative_5+ narrative_7 
  traitneedsecurity=~ tsec1+tsec2+tsec3

Micronarratives ~b1*needsecurity+traitneedsecurity+trust5
  Mainstream ~b2*needsecurity+traitneedsecurity+trust5


  needsecurity ~ gr_1
  needsecurity ~ a1*trust5
  traitneedsecurity ~ trust5
      
      
      
  needsecurity ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1
ind1 := a1*b1
ind2 := a1*b2

'


tmed.fit <- sem(tmed.model, data = forsem, estimator = "ML", missing = "FIML",
                se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(tmed.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_tmed.fit <- parameterEstimates(tmed.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,
                                         zstat = FALSE, pvalue = FALSE, output = "data.frame")

View(estimates_tmed.fit)

estimates_tmed.fit[68:69, ]



```

Freedom

```{r}
freed.model <- '
  needfreedom =~ sfree1+sfree2+sfree3
  Mainstream=~narrative_2  +narrative_4  +narrative_6  +narrative_8  
  Micronarratives=~narrative_1+narrative_3+narrative_5+ narrative_7 
  traitneedfreedom=~  tfree1+ tfree2+ tfree3

  Micronarratives ~b1*needfreedom+traitneedfreedom
  Mainstream ~b2*needfreedom+traitneedfreedom


  needfreedom ~ a1*gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1

  ind1 := a1*b1
  ind2 := a1*b2

  

'

freed.fit <- sem(freed.model, data = forsem, estimator = "ML", missing = "FIML",
                 se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(freed.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_freed.fit <- parameterEstimates(freed.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

estimates_freed.fit[61:62, ]
```

```{r}
pfad_layout<- get_layout("","", "", "","Micronarratives",
                         "","traitneedfreedom", "","","",
                         "","","","","",
                         "gr_2","","","","Mainstream",
                         "","needfreedom","","","",
                         rows = 5)

tidySEM::graph_sem(model = freed.fit, layout = pfad_layout) 

```

Freedom and trust

```{r}

frtr.model <- '
  needfreedom =~ sfree1+sfree2+sfree3
  Mainstream=~narrative_2  +narrative_4  +narrative_6  +narrative_8  
  Micronarratives=~narrative_1+narrative_3+narrative_5+ narrative_7 
  traitneedfreedom=~  tfree1+ tfree2+ tfree3

  Micronarratives ~b1*needfreedom+traitneedfreedom
  Mainstream ~b2*needfreedom+traitneedfreedom


  needfreedom ~ gr_1
  Micronarratives ~ gr_1
  Mainstream ~gr_1

  ind1 := a1*b1
  ind2 := a1*b2

  needfreedom ~ a1*trust5
  traitneedfreedom ~ trust5
      
    

'

frtr.fit <- sem(frtr.model, data = forsem, estimator = "ML", missing = "FIML",
                 se = "bootstrap",bootstrap = 5000L, parallel ="snow")
summary(frtr.fit, fit.measures=T, standardized = T, rsquare=TRUE)
estimates_frtr.fit <- parameterEstimates(frtr.fit, standardized=TRUE, boot.ci.type="perc", level=0.95,zstat = FALSE, pvalue = FALSE, output = "data.frame")

estimates_frtr.fit[66:67, ]
```

```{r}
trustaov <- aov(ssec ~trust5*gr_1, data=forsem_s)
summary(trustaov)

```

```{r}
lm(micronarratives~ trust5, data=forsem_s)
```
